# NOTE: update this with your service name
service: travel-app-api

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  tripsTableName: ${self:custom.stage}-trips
  colsTableName: ${self:custom.stage}-lists
  tasksTableName: ${self:custom.stage}-tasks

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1

  environment:
    tripsTableName: ${self:custom.tripsTableName}
    colsTableName: ${self:custom.colsTableName}
    tasksTableName: ${self:custom.tasksTableName}
    # sampleEnvVar: ${env:SAMPLE_ENV_VAR}

  # Configure access rights for the LAMBDA application
  # i.e. access dynamo DB
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource: 
        # this list specifies to get the ARN for this specific table
        - "Fn::GetAtt": [ TripsTable, Arn ] 
        - "Fn::GetAtt": [ ColsTable, Arn ]  
        - "Fn::GetAtt": [ ItemsTable, Arn ]  

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
  # S3 Bucket
  - ${file(resources/s3-bucket.yml)}
  # Cognito
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}

functions:
  # trips
  create-trip:
    handler: for-trips.create
    events:
      - http:
          path: trips
          method: post
          cors: true
          authorizer: aws_iam
  get-trip:
    handler: for-trips.get
    events:
      - http:
          path: trips/{tripId}
          method: get
          cors: true
          authorizer: aws_iam
  getall-trip:
    handler: for-trips.getall
    events:
      - http:
          path: trips
          method: get
          cors: true
          authorizer: aws_iam
  update-trip:
    handler: for-trips.update
    events:
      - http:
          path: trips/{tripId}
          method: put
          cors: true
          authorizer: aws_iam
  delete-trip:
    handler: for-trips.delete_function
    events:
      - http:
          path: trips/{tripId}
          method: delete
          cors: true
          authorizer: aws_iam
  # cols
  create-col:
    handler: for-cols.create
    events:
      - http:
          path: cols
          method: post
          cors: true
          authorizer: aws_iam
  get-col:
    handler: for-cols.get
    events:
      - http:
          path: cols/{colId}
          method: get
          cors: true
          authorizer: aws_iam
  getall-col:
    handler: for-cols.getall
    events:
      - http:
          path: cols
          method: get
          cors: true
          authorizer: aws_iam
  update-col:
    handler: for-cols.update
    events:
      - http:
          path: cols/{colId}
          method: put
          cors: true
          authorizer: aws_iam
  delete-col:
    handler: for-cols.delete_function
    events:
      - http:
          path: cols/{colId}
          method: delete
          cors: true
          authorizer: aws_iam
  # tasks
  create-task-location:
    handler: for-tasks.create_location
    events:
      - http:
          path: tasks
          method: post
          cors: true
          authorizer: aws_iam
  create-task-drive:
    handler: for-tasks.drive
    events:
      - http:
          path: tasks
          method: post
          cors: true
          authorizer: aws_iam
  get-task:
    handler: for-tasks.get
    events:
      - http:
          path: tasks/{taskId}
          method: get
          cors: true
          authorizer: aws_iam
  getall-task:
    handler: for-tasks.getall
    events:
      - http:
          path: tasks
          method: get
          cors: true
          authorizer: aws_iam
  update-task:
    handler: for-tasks.update
    events:
      - http:
          path: tasks/{taskId}
          method: put
          cors: true
          authorizer: aws_iam
  delete-task:
    handler: for-tasks.delete_function
    events:
      - http:
          path: tasks/{taskId}
          method: delete
          cors: true
          authorizer: aws_iam















































