Resources:
  TripsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tripsTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: tripId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: tripId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  ColsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.colsTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: colId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: colId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST

  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tasksTableName}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: taskId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: taskId
          KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
